CREATE OR REPLACE PROCEDURE GC.PRC_RETORNAR_NFS_WMS_GC IS
   --
   -- VERSAO 23
   --
   -- Identifica Retorno de WMS (INT_S_CAB_PEDIDO) com situacao [F] - Faturado
   -- Eh necessario que todas as NFs do pedido tenham DANFE e que o status no SEFAZ seja valido
   --
   CURSOR C_PEDIDOS_FATURADOS IS
      SELECT TRPGW.NU_PEDIDO_ORIGEM        TRPGW_NU_PEDIDO_ORIGEM,
             ISCPS.NU_SEQ                  ISCPS_NU_SEQ,
             TRPGW.CD_FIL_ROM              TRPGW_CD_FIL,
             TRPGW.ID_ROM                  TRPGW_ID_ROM,
             TRPGW.TP_PEDIDO_WMS           TRPGW_TP_PEDIDO_WMS,
             TRPGW.CD_FIL_DOCTO            TRPGW_CD_FIL_DOCTO,
             TRPGW.NR_DOCTO                TRPGW_NR_DOCTO,
             TRPGW.TP_DOCTO                TRPGW_TP_DOCTO,
             TRPGW.DT_EMIS_DOCTO           TRPGW_DT_EMIS_DOCTO,
             TRPGW.ID_TGE                  TRPGW_ID_TGE,
             TRPGW.CD_CCO                  TRPGW_CD_CCO,
             TRPGW.ID_AGRUPADOR            TRPGW_ID_AGRUPADOR,
             NVL(TRPGW.TP_AGRUPADOR,'X')   TRPGW_TP_AGRUPADOR,
             TRPGW.ID_BUSCA_ATIVA          TRPGW_ID_BUSCA_ATIVA,
             EBQ.CD_FIL_RSD                EBQ_CD_FIL_RSD,
             EBQ.ID_ROM_RSD                EBQ_ID_ROM_RSD,
             EBQ.DS_PLACA                  EBQ_DS_PLACA,
             EBQ.DT_INIC                   EBQ_DT_INIC,
             EBQ.DT_FIM                    EBQ_DT_FIM,
             EBQ.DT_FAT                    EBQ_DT_FAT,
             EBQ.DS_PLACA_VEI              EBQ_DS_PLACA_VEI,
             EBQ.CD_FIL_ESTQ               EBQ_CD_FIL_ESTQ,
             EBQ.ID_LOCAL                  EBQ_ID_LOCAL,
             EBQ.IN_PEND                   EBQ_IN_PEND,
             IECPS.NU_SEQ                  IECPS_NU_SEQ,
             IECPS.CD_EMPRESA              IECPS_CD_EMPRESA,
             IECPS.CD_DEPOSITO             IECPS_CD_DEPOSITO,
             IECPS.NU_PEDIDO_ORIGEM        IECPS_NU_PEDIDO_ORIGEM,
             IECPS.CD_CLIENTE              IECPS_CD_CLIENTE,
             IECPS.CD_CNPJ_CLIENTE         IECPS_CD_CNPJ_CLIENTE,
             IECPS.DS_CLIENTE              IECPS_DS_CLIENTE,
             IECPS.CD_CARGA                IECPS_CD_CARGA,
             IECPS.TP_PEDIDO               IECPS_TP_PEDIDO,
             IECPS.DS_TPPEDIDO             IECPS_DS_TPPEDIDO,
             IECPS.CD_PORTA                IECPS_CD_PORTA,
             IECPS.CD_TRANSPORTADORA       IECPS_CD_TRANSPORTADORA,
             IECPS.CD_CNPJ_TRANSPORTADORA  IECPS_CD_CNPJ_TRANSPORTADORA,
             IECPS.DS_TRANSPORTADORA       IECPS_DS_TRANSPORTADORA,
             IECPS.NU_DOC_ERP              IECPS_NU_DOC_ERP,
             IECPS.DS_CLIENTE_ENTREGA      IECPS_DS_CLIENTE_ENTREGA,
             IECPS.CD_CNPJ_CLIENTE_ENTREGA IECPS_CD_CNPJ_CLIENTE_ENTREGA,
             IECPS.DS_ENDERECO_ENTREGA     IECPS_DS_ENDERECO_ENTREGA,
             IECPS.NU_ENDERECO_ENTREGA     IECPS_NU_ENDERECO_ENTREGA,
             IECPS.DS_COMPLEMENTO_ENTREGA  IECPS_DS_COMPLEMENTO_ENTREGA,
             IECPS.DS_BAIRRO_ENTREGA       IECPS_DS_BAIRRO_ENTREGA,
             IECPS.DS_MUNICIPIO_ENTREGA    IECPS_DS_MUNICIPIO_ENTREGA,
             IECPS.CD_UF_ENTREGA           IECPS_CD_UF_ENTREGA,
             IECPS.CD_CEP_ENTREGA          IECPS_CD_CEP_ENTREGA,
             IECPS.NU_TELEFONE_ENTREGA     IECPS_NU_TELEFONE_ENTREGA,
             IECPS.VL_NOTA                 IECPS_VL_NOTA,
             IECPS.DT_ENTREGA              IECPS_DT_ENTREGA,
             IECPS.CD_AGENDA               IECPS_CD_AGENDA,
             IECPS.NU_SEQ_ENTREGA          IECPS_NU_SEQ_ENTREGA,
             IECPS.NU_PEDIDO               IECPS_NU_PEDIDO,
             IECPS.CD_CANAL                IECPS_CD_CANAL,
             IECPS.DS_CANAL                IECPS_DS_CANAL,
             IECPS.CD_ROTA                 IECPS_CD_ROTA,
             IECPS.DS_ROTA                 IECPS_DS_ROTA,
             IECPS.ID_SOLICITA_CONTROLE    IECPS_ID_SOLICITA_CONTROLE,
             IECPS.DT_FATURAMENTO          IECPS_DT_FATURAMENTO,
             IECPS.DT_ENTRADA              IECPS_DT_ENTRADA,
             IECPS.NU_OBJETO_POSTAGEM      IECPS_NU_OBJETO_POSTAGEM,
             IECPS.DS_OBSERVACAO           IECPS_DS_OBSERVACAO,
             IECPS.CD_MUNICIPIO_IBGE       IECPS_CD_MUNICIPIO_IBGE,
             IECPS.TP_FRETE                IECPS_TP_FRETE,
             IECPS.ID_CONTRIBUINTE_ICMS    IECPS_ID_CONTRIBUINTE_ICMS,
             IECPS.CD_PRODUTO_CATEGORIA    IECPS_CD_PRODUTO_CATEGORIA,
             IECPS.VLR_FRETE_RECEBER       IECPS_VLR_FRETE_RECEBER,
             IECPS.CD_TIPO_ENTREGA         IECPS_CD_TIPO_ENTREGA,
             IECPS.FILLER_1                IECPS_FILLER_1,
             IECPS.FILLER_2                IECPS_FILLER_2,
             IECPS.FILLER_3                IECPS_FILLER_3,
             IECPS.FILLER_4                IECPS_FILLER_4,
             IECPS.FILLER_5                IECPS_FILLER_5,
             IECPS.DS_PONTUACAO_CLIENTE    IECPS_DS_PONTUACAO_CLIENTE,
             IECPS.CD_FILIAL_VENDA         IECPS_CD_FILIAL_VENDA,
             IECPS.DS_MODAL_FRETE          IECPS_DS_MODAL_FRETE,
             IECPS.NU_VOLUME_TRANSPORTE    IECPS_NU_VOLUME_TRANSPORTE,
             IECPS.QT_PEDIDOS_CARGA        IECPS_QT_PEDIDOS_CARGA,
             ISCPS.NU_ETIQUETA_MASTER      ISCPS_NU_ETIQUETA_MASTER,
             IECPS.NU_ORDEM_COMPRA         IECPS_NU_ORDEM_COMPRA,
             IECPS.TP_SERVICO_ENTREGA      IECPS_TP_SERVICO_ENTREGA,
             IECPS.DT_PAGAMENTO_PEDIDO     IECPS_DT_PAGAMENTO_PEDIDO,
             IECPS.DS_PLACA                IECPS_DS_PLACA,
             IECPS.ROWID                   CHAVE_IECPS,
             ISCPS.ROWID                   CHAVE_ISCPS
        FROM WMS.INT_S_CAB_PEDIDO_SAIDA    ISCPS,
             WMS.INT_E_CAB_PEDIDO_SAIDA    IECPS,
             WMS.T_RELACIONA_PEDIDO_GC_WMS TRPGW,
             GC.EMBARQUE                   EBQ
       WHERE ISCPS.ID_PROCESSADO = 'F' --FATURADO
         AND ISCPS.NU_PEDIDO_ORIGEM = TRPGW.NU_PEDIDO_ORIGEM
         AND ISCPS.NU_PEDIDO_ORIGEM = IECPS.NU_PEDIDO_ORIGEM
         AND ISCPS.CD_CLIENTE = IECPS.CD_CLIENTE
         AND ISCPS.CD_EMPRESA = IECPS.CD_EMPRESA
         AND ISCPS.CD_DEPOSITO = IECPS.CD_DEPOSITO
         AND IECPS.CD_SITUACAO = 1
         AND IECPS.ID_PROCESSADO = 'S'
         AND TRPGW.CD_FIL_ROM = EBQ.CD_FIL_RSD
         AND TRPGW.ID_ROM = EBQ.ID_ROM_RSD
         AND ISCPS.FILLER_5 = EBQ.DS_PLACA
         AND GC.RET_COMPLETUDE_NFS_TARGET(EBQ.CD_FIL_RSD,
                                          EBQ.ID_ROM_RSD,
                                          EBQ.DS_PLACA,
                                          TRPGW.ID_AGRUPADOR,
                                          NVL(TRPGW.TP_AGRUPADOR, 'X'),
                                          TRPGW.TP_PEDIDO_WMS,
                                          TRPGW.TP_DOCTO,
                                          TRPGW.CD_FIL_DOCTO,
                                          TRPGW.NR_DOCTO,
                                          TRPGW.DT_EMIS_DOCTO,
                                          TRPGW.CD_CCO,
                                          TRPGW.NU_PEDIDO_ORIGEM,
                                          ISCPS.NU_SEQ) = 'S'
       ORDER BY ISCPS.NU_SEQ;
--
-- RELAÇÃO DE NOTAS FISCAIS QUE DEVEM SER RETORNADAS DE ACORDO COM OS MESMOS CRITERIOS DA COMPLETUDE
-- EXCETO PELA TRATATIVA APLICADA NESTE CONTEXTO PARA REMESSAS A ORDEM/BRINDES/LISTA DE CASAMENTO
--
   CURSOR C_NFS_PEDIDOS(P_CD_FIL_RSD    GC.NF_SAIDA.CD_FIL_RSD_EBQ%TYPE,
                        P_ID_ROM_RSD    GC.NF_SAIDA.ID_ROM_RSD_EBQ%TYPE,
                        P_DS_PLACA      GC.NF_SAIDA.DS_PLACA_EBQ%TYPE,
                        P_ID_AGRUPADOR  WMS.T_RELACIONA_PEDIDO_GC_WMS.ID_AGRUPADOR%TYPE,
                        P_TP_AGRUPADOR  WMS.T_RELACIONA_PEDIDO_GC_WMS.TP_AGRUPADOR%TYPE,
                        P_TP_PEDIDO_WMS WMS.T_RELACIONA_PEDIDO_GC_WMS.TP_PEDIDO_WMS%TYPE,
                        P_TP_DOCTO      WMS.T_RELACIONA_PEDIDO_GC_WMS.TP_DOCTO%TYPE,
                        P_CD_FIL_DOCTO  WMS.T_RELACIONA_PEDIDO_GC_WMS.CD_FIL_DOCTO%TYPE,
                        P_NR_DOCTO      WMS.T_RELACIONA_PEDIDO_GC_WMS.NR_DOCTO%TYPE,
                        P_DT_EMIS_DOCTO WMS.T_RELACIONA_PEDIDO_GC_WMS.DT_EMIS_DOCTO%TYPE,
                        P_CD_CCO        WMS.T_RELACIONA_PEDIDO_GC_WMS.CD_CCO%TYPE,
                        P_NU_SEQ           WMS.INT_S_CAB_PEDIDO_SAIDA.NU_SEQ%TYPE,
                        P_NU_PEDIDO_ORIGEM WMS.INT_S_CAB_PEDIDO_SAIDA.NU_PEDIDO_ORIGEM%TYPE) IS
SELECT NFS.DT_EMIS
       ,NFS.CD_FIL
       ,NFS.NR_NF
       ,NFS.DS_SER
       ,NFS.NR_SUBSER
       ,NFS.CD_NAT_OPER_NZN
       ,NFS.CD_TIPO_NF_NZN
       ,NFS.VM_LIQ_MERC
       ,SUBSTR(GC.RET_CHAVE_NF_SAIDA(NFS.DT_EMIS,
                                    NFS.CD_FIL,
                                    NFS.NR_NF,
                                    NFS.DS_SER,
                                    NFS.NR_SUBSER,
                                    'S'),
              1,
              50) DANFE
        ,DECODE (NFF.IN_PEND_ARQ_NF_ELETR, NULL, 'S', 'N') CK_STATUS_ARQ_TXT
        ,NFF.NM_ARQ_TXT_NF_ELETR
        ,NFF.TX_OCOR_GERA_ARQ_NF_ELETR
  FROM (SELECT NFS.DT_EMIS,
               NFS.CD_FIL,
               NFS.NR_NF,
               NFS.DS_SER,
               NFS.NR_SUBSER,
               NFS.CD_NAT_OPER_NZN,
               NFS.CD_TIPO_NF_NZN,
               NFS.CD_FIL_RSD_EBQ,
               NFS.ID_ROM_RSD_EBQ,
               NFS.DS_PLACA_EBQ,
               NFS.VM_LIQ_MERC,
               NFS.CD_FIL_PVD,
               NFS.DT_EMIS_PVD,
               NFS.NR_PVD,
               NFS.CD_FIL_PSO,
               NFS.NR_PED_PSO,
               NFS.CD_FIL_REQ,
               NFS.NR_REQ,
               NFS.CD_FIL_RUC,
               NFS.NR_REQ_RUC,
               NFS.CD_CCO_RUC,
               NFS.CD_FIL_PRINC
          FROM GC.NF_SAIDA NFS
         WHERE NFS.DT_EMIS >= ADD_MONTHS(SYSDATE, -6)
           AND NFS.DT_CANC IS NULL) NFS, GC.ROMANEIO_SEPARACAO RSD, GC.NF_FORMULARIO NFF
 WHERE RSD.CD_FIL         = P_CD_FIL_RSD
   AND RSD.ID_ROM         = P_ID_ROM_RSD
   AND NFS.CD_FIL_RSD_EBQ = P_CD_FIL_RSD
   AND NFS.ID_ROM_RSD_EBQ = P_ID_ROM_RSD
   AND NFS.DS_PLACA_EBQ   = P_DS_PLACA
   AND NFF.DT_EMIS        = NFS.DT_EMIS
   AND NFF.CD_FIL         = NFS.CD_FIL
   AND NFF.NR_NF          = NFS.NR_NF
   AND NFF.NR_SUBSER      = NFS.NR_SUBSER
   AND NFF.DS_SER         = NFS.DS_SER
   AND NFF.IN_ENTR_SAIDA  = 'S'
   AND NFS.CD_FIL_PRINC IS NULL --RETORNA SOMENTE A NOTA PRINCIPAL QUANDO FOR REMESSAS A ORDEM/BRINDES/LISTA DE CASAMENTO
   AND ((((P_TP_AGRUPADOR = 'REQ' -- PEDIDOS REQ (REQ E RET)
               AND ((NFS.CD_FIL_REQ = RSD.CD_FIL_REQ AND
               NFS.NR_REQ =P_ID_AGRUPADOR) OR
                     (EXISTS (SELECT 1 FROM WMS.T_RELACIONA_RET_PSO TRRP
               WHERE TRRP.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
               AND   TRRP.NU_SEQ_ISCPS     = P_NU_SEQ
               AND   TRRP.CD_FIL           = NFS.CD_FIL_PSO
               AND   TRRP.NR_PED           = NFS.NR_PED_PSO)))) OR
       (P_TP_AGRUPADOR != 'REQ' AND
       ((P_TP_DOCTO = 'PVD' AND NFS.CD_FIL_PVD = P_CD_FIL_DOCTO AND
       NFS.DT_EMIS_PVD = P_DT_EMIS_DOCTO AND NFS.NR_PVD = P_NR_DOCTO) OR
       (P_TP_DOCTO = 'POS' AND NFS.CD_FIL_PSO = P_CD_FIL_DOCTO AND
       NFS.NR_PED_PSO = P_NR_DOCTO) OR
       (P_TP_DOCTO = 'RUC' AND NFS.CD_FIL_RUC = P_CD_FIL_DOCTO AND
       NFS.NR_REQ_RUC = P_NR_DOCTO AND NFS.CD_CCO_RUC = P_CD_CCO) OR
       (P_TP_DOCTO = 'SPV')))) AND NOT EXISTS
        (SELECT 1
            FROM ITEM_PV_FAT_ITEM_NF_TRANSF IPVT
           WHERE IPVT.NR_PV_IPV = P_NR_DOCTO
             AND IPVT.CD_FIL_IPV = P_CD_FIL_DOCTO
             AND IPVT.DT_EMIS_IPV = P_DT_EMIS_DOCTO
             AND 'PVP' = P_TP_PEDIDO_WMS
             AND 'PDS' = P_TP_AGRUPADOR)) OR
       (EXISTS (SELECT 1
                   FROM ITEM_PV_FAT_ITEM_NF_TRANSF IPVT
                  WHERE IPVT.NR_PV_IPV = P_NR_DOCTO
                    AND IPVT.CD_FIL_IPV = P_CD_FIL_DOCTO
                    AND IPVT.DT_EMIS_IPV = P_DT_EMIS_DOCTO
                    AND 'PVP' = P_TP_PEDIDO_WMS
                    AND 'PDS' = P_TP_AGRUPADOR)));
--
   -- Identifica itens (INT_S_DET_PEDIDO) com situacao [F] - Faturado
   --
  CURSOR C_ITENS_NFS_PEDIDOS(P_DT_EMIS          GC.ITEM_NF_SAIDA_PRODUTO.DT_EMIS%TYPE,
                             P_CD_FIL           GC.ITEM_NF_SAIDA_PRODUTO.CD_FIL%TYPE,
                             P_NR_NF            GC.ITEM_NF_SAIDA_PRODUTO.NR_NF%TYPE,
                             P_DS_SER           GC.ITEM_NF_SAIDA_PRODUTO.DS_SER%TYPE,
                             P_NR_SUBSER        GC.ITEM_NF_SAIDA_PRODUTO.NR_SUBSER%TYPE,
                             P_NU_SEQ           WMS.INT_S_CAB_PEDIDO_SAIDA.NU_SEQ%TYPE,
                             P_NU_PEDIDO_ORIGEM WMS.INT_S_CAB_PEDIDO_SAIDA.NU_PEDIDO_ORIGEM%TYPE,
                             P_TP_DOCTO         WMS.T_RELACIONA_PEDIDO_GC_WMS.TP_DOCTO%TYPE) IS
SELECT TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS') ISP_DT_NOTA_FISCAL,
       ISP.CD_FIL ISP_CD_FIL,
       ISP.NR_NF ISP_NU_NOTA,
       ISP.DS_SER ISP_NU_SERIE_NOTA,
       ISP.NR_SUBSER ISP_NR_SUBSER,
       ISP.NFS_CD_NAT_OPER_NZN ISP_CFOP,
       SUM(NVL(ISP.QT_ITEM, 0)) ISP_QT_ITEM,
       SUM(NVL(ISP.VM_UNIT, 0)) ISP_VM_UNIT,
       SUM(NVL(ISP.VM_LIQ_MERC, 0)) ISP_VM_LIQ_MERC,
       ISP.ID_PROD ISP_ID_PROD,
       ISDPS.NU_SEQ ISDPS_NU_SEQ,
       ISDPS.ROWID CHAVE_ISDPS,
       IEDPS.NU_SEQ IEDPS_NU_SEQ,
       IEDPS.CD_EMPRESA IEDPS_CD_EMPRESA,
       IEDPS.CD_DEPOSITO IEDPS_CD_DEPOSITO,
       IEDPS.NU_PEDIDO_ORIGEM IEDPS_NU_PEDIDO_ORIGEM,
       IEDPS.CD_CLIENTE IEDPS_CD_CLIENTE,
       IEDPS.NU_ITEM_CORP IEDPS_NU_ITEM_CORP,
       IEDPS.NU_LOTE IEDPS_NU_LOTE,
       IEDPS.NU_PEDIDO IEDPS_NU_PEDIDO,
       IEDPS.ID_EMBALAGEM_PRESENTE IEDPS_ID_EMBALAGEM_PRESENTE,
       IEDPS.CAMPANHA IEDPS_CAMPANHA,
       IEDPS.DS_AREA_ERP IEDPS_DS_AREA_ERP,
       IEDPS.FILLER_1 IEDPS_FILLER_1,
       IEDPS.FILLER_2 IEDPS_FILLER_2,
       IEDPS.FILLER_3 IEDPS_FILLER_3,
       IEDPS.FILLER_4 IEDPS_FILLER_4,
       IEDPS.FILLER_5 IEDPS_FILLER_5,
       IEDPS.CD_CARGA IEDPS_CD_CARGA,
       ISDPS.NU_ETIQUETA_MASTER ISDPS_NU_ETIQUETA_MASTER,
       IEDPS.DS_PRODUTO_PERSONALIZADO IEDPS_DS_PRODUTO_PERSONALIZADO,
       IEDPS.DS_OBSERVACAO IEDPS_DS_OBSERVACAO,
       IEDPS.NU_CTRL_ITEM IEDPS_NU_CTRL_ITEM,
       SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                    ISP.CD_FIL,
                                    ISP.NR_NF,
                                    ISP.DS_SER,
                                    ISP.NR_SUBSER,
                                    'S'),
              1,
              50) ISP_DANFE,
       IEDPS.ROWID CHAVE_IEDPS
  FROM GC.ITEM_NF_SAIDA_PRODUTO      ISP,
       WMS.INT_S_DET_PEDIDO_SAIDA    ISDPS,
       WMS.INT_E_DET_PEDIDO_SAIDA    IEDPS,
       WMS.T_RELACIONA_PEDIDO_GC_WMS TRPGW
 WHERE 'SPV' <> P_TP_DOCTO
   AND ISP.DT_EMIS = P_DT_EMIS
   AND ISP.CD_FIL = P_CD_FIL
   AND ISP.NR_NF = P_NR_NF
   AND ISP.DS_SER = P_DS_SER
   AND ISP.NR_SUBSER = P_NR_SUBSER
   AND TRPGW.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND ISP.ID_PROD = ISDPS.CD_PRODUTO
   AND NOT EXISTS
 (SELECT 1
          FROM ITEM_PV_FAT_ITEM_NF_TRANSF IPVT
         WHERE IPVT.NR_PV_IPV = TRPGW.NR_DOCTO
           AND IPVT.CD_FIL_IPV = TRPGW.CD_FIL_DOCTO
           AND IPVT.DT_EMIS_IPV = TRPGW.DT_EMIS_DOCTO
           AND IPVT.DT_EMIS_ISP = ISP.DT_EMIS
           AND IPVT.CD_FIL_ISP = ISP.CD_FIL
           AND IPVT.NR_NF_ISP = ISP.NR_NF
           AND IPVT.DS_SER_ISP = ISP.DS_SER
           AND IPVT.NR_SUBSER_ISP = ISP.NR_SUBSER
           AND 'PVP' = TRPGW.TP_PEDIDO_WMS
           AND 'PDS' = TRPGW.TP_AGRUPADOR)
   AND ((ISP.NR_ITEM_IPV IS NOT NULL AND
       ISP.NR_ITEM_IPV = ISDPS.NU_ITEM_CORP) OR (ISP.NR_ITEM_IPV IS NULL))
   AND ISDPS.NU_SEQ = P_NU_SEQ
   AND ISDPS.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND ISDPS.CD_SITUACAO = 57 --EXPEDIDO
   AND ISDPS.ID_PROCESSADO = 'F' --FATURADO
   AND IEDPS.CD_SITUACAO = 1
   AND IEDPS.ID_PROCESSADO = 'S'
   AND ISDPS.NU_PEDIDO_ORIGEM = IEDPS.NU_PEDIDO_ORIGEM
   AND ISDPS.CD_CLIENTE = IEDPS.CD_CLIENTE
   AND ISDPS.CD_EMPRESA = IEDPS.CD_EMPRESA
   AND ISDPS.CD_DEPOSITO = IEDPS.CD_DEPOSITO
   AND ISDPS.CD_PRODUTO = IEDPS.CD_PRODUTO
   AND ISDPS.NU_ITEM_CORP = IEDPS.NU_ITEM_CORP
 GROUP BY TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS'),
          ISP.CD_FIL,
          ISP.NR_NF,
          ISP.DS_SER,
          ISP.NR_SUBSER,
          ISP.NFS_CD_NAT_OPER_NZN,
          ISP.ID_PROD,
          ISDPS.NU_SEQ,
          ISDPS.ROWID,
          IEDPS.NU_SEQ,
          IEDPS.CD_EMPRESA,
          IEDPS.CD_DEPOSITO,
          IEDPS.NU_PEDIDO_ORIGEM,
          IEDPS.CD_CLIENTE,
          IEDPS.NU_ITEM_CORP,
          IEDPS.NU_LOTE,
          IEDPS.NU_PEDIDO,
          IEDPS.ID_EMBALAGEM_PRESENTE,
          IEDPS.CAMPANHA,
          IEDPS.DS_AREA_ERP,
          IEDPS.FILLER_1,
          IEDPS.FILLER_2,
          IEDPS.FILLER_3,
          IEDPS.FILLER_4,
          IEDPS.FILLER_5,
          IEDPS.CD_CARGA,
          ISDPS.NU_ETIQUETA_MASTER,
          IEDPS.DS_PRODUTO_PERSONALIZADO,
          IEDPS.DS_OBSERVACAO,
          IEDPS.NU_CTRL_ITEM,
          SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                       ISP.CD_FIL,
                                       ISP.NR_NF,
                                       ISP.DS_SER,
                                       ISP.NR_SUBSER,
                                       'S'),
                 1,
                 50),
          IEDPS.ROWID
UNION ALL
SELECT TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS') ISP_DT_NOTA_FISCAL,
       ISP.CD_FIL ISP_CD_FIL,
       ISP.NR_NF ISP_NU_NOTA,
       ISP.DS_SER ISP_NU_SERIE_NOTA,
       ISP.NR_SUBSER ISP_NR_SUBSER,
       ISP.NFS_CD_NAT_OPER_NZN ISP_CFOP,
       SUM(NVL(ISP.QT_ITEM, 0)) ISP_QT_ITEM,
       SUM(NVL(ISP.VM_UNIT, 0)) ISP_VM_UNIT,
       SUM(NVL(ISP.VM_LIQ_MERC, 0)) ISP_VM_LIQ_MERC,
       ISP.ID_PROD ISP_ID_PROD,
       ISDPS.NU_SEQ ISDPS_NU_SEQ,
       ISDPS.ROWID CHAVE_ISDPS,
       IEDPS.NU_SEQ IEDPS_NU_SEQ,
       IEDPS.CD_EMPRESA IEDPS_CD_EMPRESA,
       IEDPS.CD_DEPOSITO IEDPS_CD_DEPOSITO,
       IEDPS.NU_PEDIDO_ORIGEM IEDPS_NU_PEDIDO_ORIGEM,
       IEDPS.CD_CLIENTE IEDPS_CD_CLIENTE,
       IEDPS.NU_ITEM_CORP IEDPS_NU_ITEM_CORP,
       IEDPS.NU_LOTE IEDPS_NU_LOTE,
       IEDPS.NU_PEDIDO IEDPS_NU_PEDIDO,
       IEDPS.ID_EMBALAGEM_PRESENTE IEDPS_ID_EMBALAGEM_PRESENTE,
       IEDPS.CAMPANHA IEDPS_CAMPANHA,
       IEDPS.DS_AREA_ERP IEDPS_DS_AREA_ERP,
       IEDPS.FILLER_1 IEDPS_FILLER_1,
       IEDPS.FILLER_2 IEDPS_FILLER_2,
       IEDPS.FILLER_3 IEDPS_FILLER_3,
       IEDPS.FILLER_4 IEDPS_FILLER_4,
       IEDPS.FILLER_5 IEDPS_FILLER_5,
       IEDPS.CD_CARGA IEDPS_CD_CARGA,
       ISDPS.NU_ETIQUETA_MASTER ISDPS_NU_ETIQUETA_MASTER,
       IEDPS.DS_PRODUTO_PERSONALIZADO IEDPS_DS_PRODUTO_PERSONALIZADO,
       IEDPS.DS_OBSERVACAO IEDPS_DS_OBSERVACAO,
       IEDPS.NU_CTRL_ITEM IEDPS_NU_CTRL_ITEM,
       SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                    ISP.CD_FIL,
                                    ISP.NR_NF,
                                    ISP.DS_SER,
                                    ISP.NR_SUBSER,
                                    'S'),
              1,
              50) ISP_DANFE,
       IEDPS.ROWID CHAVE_IEDPS
  FROM GC.ITEM_NF_SAIDA_PRODUTO      ISP,
       WMS.INT_S_DET_PEDIDO_SAIDA    ISDPS,
       WMS.INT_E_DET_PEDIDO_SAIDA    IEDPS,
       GC.ITEM_PV_FAT_ITEM_NF_TRANSF IPVT,
       WMS.T_RELACIONA_PEDIDO_GC_WMS TRPGW
 WHERE 'SPV' <> P_TP_DOCTO
   AND ISP.DT_EMIS = P_DT_EMIS
   AND ISP.CD_FIL = P_CD_FIL
   AND ISP.NR_NF = P_NR_NF
   AND ISP.DS_SER = P_DS_SER
   AND ISP.NR_SUBSER = P_NR_SUBSER
   AND ISP.ID_PROD = ISDPS.CD_PRODUTO
   AND TRPGW.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND 'PVP' = TRPGW.TP_PEDIDO_WMS
   AND 'PDS' = TRPGW.TP_AGRUPADOR
   AND IPVT.CD_FIL_IPV = TRPGW.CD_FIL_DOCTO
   AND IPVT.DT_EMIS_IPV = TRPGW.DT_EMIS_DOCTO
   AND IPVT.NR_PV_IPV = TRPGW.NR_DOCTO
   AND IPVT.DT_EMIS_ISP = ISP.DT_EMIS
   AND IPVT.CD_FIL_ISP = ISP.CD_FIL
   AND IPVT.NR_NF_ISP = ISP.NR_NF
   AND IPVT.DS_SER_ISP = ISP.DS_SER
   AND IPVT.NR_SUBSER_ISP = ISP.NR_SUBSER
   AND IPVT.NR_ITEM_ISP = ISP.NR_ITEM
   AND IPVT.NR_ITEM_IPV = ISDPS.NU_ITEM_CORP
   AND ISDPS.NU_SEQ = P_NU_SEQ
   AND ISDPS.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND ISDPS.CD_SITUACAO = 57 --EXPEDIDO
   AND ISDPS.ID_PROCESSADO = 'F' --FATURADO
   AND IEDPS.CD_SITUACAO = 1
   AND IEDPS.ID_PROCESSADO = 'S'
   AND ISDPS.NU_PEDIDO_ORIGEM = IEDPS.NU_PEDIDO_ORIGEM
   AND ISDPS.CD_CLIENTE = IEDPS.CD_CLIENTE
   AND ISDPS.CD_EMPRESA = IEDPS.CD_EMPRESA
   AND ISDPS.CD_DEPOSITO = IEDPS.CD_DEPOSITO
   AND ISDPS.CD_PRODUTO = IEDPS.CD_PRODUTO
   AND ISDPS.NU_ITEM_CORP = IEDPS.NU_ITEM_CORP
 GROUP BY TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS'),
          ISP.CD_FIL,
          ISP.NR_NF,
          ISP.DS_SER,
          ISP.NR_SUBSER,
          ISP.NFS_CD_NAT_OPER_NZN,
          ISP.ID_PROD,
          ISDPS.NU_SEQ,
          ISDPS.ROWID,
          IEDPS.NU_SEQ,
          IEDPS.CD_EMPRESA,
          IEDPS.CD_DEPOSITO,
          IEDPS.NU_PEDIDO_ORIGEM,
          IEDPS.CD_CLIENTE,
          IEDPS.NU_ITEM_CORP,
          IEDPS.NU_LOTE,
          IEDPS.NU_PEDIDO,
          IEDPS.ID_EMBALAGEM_PRESENTE,
          IEDPS.CAMPANHA,
          IEDPS.DS_AREA_ERP,
          IEDPS.FILLER_1,
          IEDPS.FILLER_2,
          IEDPS.FILLER_3,
          IEDPS.FILLER_4,
          IEDPS.FILLER_5,
          IEDPS.CD_CARGA,
          ISDPS.NU_ETIQUETA_MASTER,
          IEDPS.DS_PRODUTO_PERSONALIZADO,
          IEDPS.DS_OBSERVACAO,
          IEDPS.NU_CTRL_ITEM,
          SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                       ISP.CD_FIL,
                                       ISP.NR_NF,
                                       ISP.DS_SER,
                                       ISP.NR_SUBSER,
                                       'S'),
                 1,
                 50),
          IEDPS.ROWID
UNION ALL
SELECT TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS') ISP_DT_NOTA_FISCAL,
       ISP.CD_FIL ISP_CD_FIL,
       ISP.NR_NF ISP_NU_NOTA,
       ISP.DS_SER ISP_NU_SERIE_NOTA,
       ISP.NR_SUBSER ISP_NR_SUBSER,
       ISP.NFS_CD_NAT_OPER_NZN ISP_CFOP,
       SUM(NVL(ISP.QT_ITEM, 0)) ISP_QT_ITEM,
       SUM(NVL(ISP.VM_UNIT, 0)) ISP_VM_UNIT,
       SUM(NVL(ISP.VM_LIQ_MERC, 0)) ISP_VM_LIQ_MERC,
       ISP.ID_PROD ISP_ID_PROD,
       ISDPS.NU_SEQ ISDPS_NU_SEQ,
       ISDPS.ROWID CHAVE_ISDPS,
       IEDPS.NU_SEQ IEDPS_NU_SEQ,
       IEDPS.CD_EMPRESA IEDPS_CD_EMPRESA,
       IEDPS.CD_DEPOSITO IEDPS_CD_DEPOSITO,
       IEDPS.NU_PEDIDO_ORIGEM IEDPS_NU_PEDIDO_ORIGEM,
       IEDPS.CD_CLIENTE IEDPS_CD_CLIENTE,
       IEDPS.NU_ITEM_CORP IEDPS_NU_ITEM_CORP,
       IEDPS.NU_LOTE IEDPS_NU_LOTE,
       IEDPS.NU_PEDIDO IEDPS_NU_PEDIDO,
       IEDPS.ID_EMBALAGEM_PRESENTE IEDPS_ID_EMBALAGEM_PRESENTE,
       IEDPS.CAMPANHA IEDPS_CAMPANHA,
       IEDPS.DS_AREA_ERP IEDPS_DS_AREA_ERP,
       IEDPS.FILLER_1 IEDPS_FILLER_1,
       IEDPS.FILLER_2 IEDPS_FILLER_2,
       IEDPS.FILLER_3 IEDPS_FILLER_3,
       IEDPS.FILLER_4 IEDPS_FILLER_4,
       IEDPS.FILLER_5 IEDPS_FILLER_5,
       IEDPS.CD_CARGA IEDPS_CD_CARGA,
       ISDPS.NU_ETIQUETA_MASTER ISDPS_NU_ETIQUETA_MASTER,
       IEDPS.DS_PRODUTO_PERSONALIZADO IEDPS_DS_PRODUTO_PERSONALIZADO,
       IEDPS.DS_OBSERVACAO IEDPS_DS_OBSERVACAO,
       IEDPS.NU_CTRL_ITEM IEDPS_NU_CTRL_ITEM,
       SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                    ISP.CD_FIL,
                                    ISP.NR_NF,
                                    ISP.DS_SER,
                                    ISP.NR_SUBSER,
                                    'S'),
              1,
              50) ISP_DANFE,
       IEDPS.ROWID CHAVE_IEDPS
  FROM GC.ITEM_NF_SAIDA_PRODUTO       ISP,
       WMS.INT_S_DET_PEDIDO_SAIDA     ISDPS,
       WMS.INT_E_DET_PEDIDO_SAIDA     IEDPS,
       WMS.T_RELACIONA_PEDIDO_GC_WMS  TRPGW,
       GC.ITEM_SERVICO_POS_VENDA      ISV,
       GC.ACAO_ITEM_SERVICO_POS_VENDA AIS,
       GC.ITEM_PED_OUTRA_SAIDA        IPX
 WHERE 'SPV' = P_TP_DOCTO
   AND ISP.DT_EMIS = P_DT_EMIS
   AND ISP.CD_FIL = P_CD_FIL
   AND ISP.NR_NF = P_NR_NF
   AND ISP.DS_SER = P_DS_SER
   AND ISP.NR_SUBSER = P_NR_SUBSER
   AND ISP.ID_PROD = ISDPS.CD_PRODUTO
   AND TRPGW.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND ISDPS.NU_SEQ = P_NU_SEQ
   AND ISDPS.NU_PEDIDO_ORIGEM = P_NU_PEDIDO_ORIGEM
   AND ISDPS.NU_PEDIDO_ORIGEM = TRPGW.NU_PEDIDO_ORIGEM
   AND TRPGW.TP_AGRUPADOR = 'PDS'
   AND TRPGW.TP_DOCTO = 'SPV'
   AND ISDPS.CD_SITUACAO = 57 --EXPEDIDO
   AND ISDPS.ID_PROCESSADO = 'F' --FATURADO
   AND IEDPS.CD_SITUACAO = 1
   AND IEDPS.ID_PROCESSADO = 'S'
   AND ISDPS.NU_PEDIDO_ORIGEM = IEDPS.NU_PEDIDO_ORIGEM
   AND ISDPS.CD_CLIENTE = IEDPS.CD_CLIENTE
   AND ISDPS.CD_EMPRESA = IEDPS.CD_EMPRESA
   AND ISDPS.CD_DEPOSITO = IEDPS.CD_DEPOSITO
   AND ISDPS.CD_PRODUTO = IEDPS.CD_PRODUTO
   AND ISDPS.NU_ITEM_CORP = IEDPS.NU_ITEM_CORP
   AND TRPGW.NR_DOCTO = ISV.NR_SOLIC
   AND ISV.NR_SOLIC = AIS.NR_SOLIC_ISV
   AND ISV.NR_SEQ_ITEM = ISDPS.NU_ITEM_CORP
   AND ISV.NR_SEQ_ITEM = AIS.NR_SEQ_ITEM_ISV
   AND AIS.NR_ACAO = IPX.NR_ACAO_AIS
   AND ISP.CD_FIL_IPX = IPX.CD_FIL
   AND ISP.NR_PED_IPX = IPX.NR_PED
   AND ISP.NR_ITEM_IPX = IPX.NR_ITEM
   AND ISP.ID_PROD_IPX = IPX.ID_PROD
 GROUP BY TO_CHAR(ISP.DT_EMIS, 'DD/MM/YYYY HH24:MI:SS'),
          ISP.CD_FIL,
          ISP.NR_NF,
          ISP.DS_SER,
          ISP.NR_SUBSER,
          ISP.NFS_CD_NAT_OPER_NZN,
          ISP.ID_PROD,
          ISDPS.NU_SEQ,
          ISDPS.ROWID,
          IEDPS.NU_SEQ,
          IEDPS.CD_EMPRESA,
          IEDPS.CD_DEPOSITO,
          IEDPS.NU_PEDIDO_ORIGEM,
          IEDPS.CD_CLIENTE,
          IEDPS.NU_ITEM_CORP,
          IEDPS.NU_LOTE,
          IEDPS.NU_PEDIDO,
          IEDPS.ID_EMBALAGEM_PRESENTE,
          IEDPS.CAMPANHA,
          IEDPS.DS_AREA_ERP,
          IEDPS.FILLER_1,
          IEDPS.FILLER_2,
          IEDPS.FILLER_3,
          IEDPS.FILLER_4,
          IEDPS.FILLER_5,
          IEDPS.CD_CARGA,
          ISDPS.NU_ETIQUETA_MASTER,
          IEDPS.DS_PRODUTO_PERSONALIZADO,
          IEDPS.DS_OBSERVACAO,
          IEDPS.NU_CTRL_ITEM,
          SUBSTR(GC.RET_CHAVE_NF_SAIDA(ISP.DT_EMIS,
                                       ISP.CD_FIL,
                                       ISP.NR_NF,
                                       ISP.DS_SER,
                                       ISP.NR_SUBSER,
                                       'S'),
                 1,
                 50),
          IEDPS.ROWID
 ORDER BY 19;
   --
   R_PEDIDOS_FATURADOS C_PEDIDOS_FATURADOS%ROWTYPE;
   R_NFS_PEDIDOS       C_NFS_PEDIDOS%ROWTYPE;
   R_ITENS_NFS_PEDIDOS C_ITENS_NFS_PEDIDOS%ROWTYPE;
   --
   P_REC_CABPED WMS.INT_E_CAB_PEDIDO_SAIDA%ROWTYPE;
   P_REC_DETPED WMS.INT_E_DET_PEDIDO_SAIDA%ROWTYPE;
   --
   V_PROCESSAMENTO_OK_SN VARCHAR2(01) := 'S';
   V_GRAVAR_CABEC        VARCHAR2(01) := 'N';
   V_QTDE_REGS           NUMBER := 0;
   --
   V_ERRO_CAB   WMS.INT_S_CAB_PEDIDO_SAIDA.DS_PROCESSADO%TYPE;
   V_ERRO_DET   WMS.INT_S_DET_PEDIDO_SAIDA.DS_PROCESSADO%TYPE;
   V_STATUS_CAB VARCHAR2(1) := 'F';
   V_STATUS_DET VARCHAR2(1) := 'F';
   --
   D_SQLERRM GC.GC_MSG.TX_OCOR%TYPE;
   D_ID_MSG  GC.GC_MSG.ID_MSG%TYPE;
   P_MSG     GC.GC_MSG%ROWTYPE;
   --
BEGIN
   --
   -- OBJETIVO..: REALIZAR A GRAVAÇÃO DE DADOS DE RETORNO DE FATURAMENTO DO GC PARA O WMS (WMS.INT_E_CAB_PEDIDO_SAIDA / WMS.INT_E_DET_PEDIDO_SAIDA)
   -- AUTOR/DATA: JEAN JEYME COSTA DEBTIL, 01/09/2020
   -- ALTERACOES:
   -- 26/10/2020 - INCLUÍDA VERIFICAÇÃO DE NFS DE ACORDO COM DANFE (GC.RET_COMPLETUDE_NFS_TARGET)
   -- 19/11/2020 - RECRIAÇÃO DO CURSOR C_NFS_PEDIDOS
   --
   -- EFETUAR A GRAVAÇÃO DE REGISTROS CASO O CONJUNTO DE VARIAVEIS NECESSARIAS FORAM CORRETAMENTE INFORMADAS
   --
   --
   FOR R_PEDIDOS_FATURADOS IN C_PEDIDOS_FATURADOS
   LOOP
      BEGIN
         --
         V_PROCESSAMENTO_OK_SN := 'S';
         --
         V_GRAVAR_CABEC := 'S';
         --
         V_QTDE_REGS := 0;
         --
         FOR R_NFS_PEDIDOS IN C_NFS_PEDIDOS(R_PEDIDOS_FATURADOS.EBQ_CD_FIL_RSD,
                                          R_PEDIDOS_FATURADOS.EBQ_ID_ROM_RSD,
                                          R_PEDIDOS_FATURADOS.EBQ_DS_PLACA,
                                          R_PEDIDOS_FATURADOS.TRPGW_ID_AGRUPADOR,
                                          R_PEDIDOS_FATURADOS.TRPGW_TP_AGRUPADOR,
                                          R_PEDIDOS_FATURADOS.TRPGW_TP_PEDIDO_WMS,
                                          R_PEDIDOS_FATURADOS.TRPGW_TP_DOCTO,
                                          R_PEDIDOS_FATURADOS.TRPGW_CD_FIL_DOCTO,
                                          R_PEDIDOS_FATURADOS.TRPGW_NR_DOCTO,
                                          R_PEDIDOS_FATURADOS.TRPGW_DT_EMIS_DOCTO,
                                          R_PEDIDOS_FATURADOS.TRPGW_CD_CCO,
                                          R_PEDIDOS_FATURADOS.ISCPS_NU_SEQ,
                                          R_PEDIDOS_FATURADOS.TRPGW_NU_PEDIDO_ORIGEM) LOOP
            --
            -- Grava itens de acordo com linhas de retorno
            --
            FOR R_ITENS_NFS_PEDIDOS IN C_ITENS_NFS_PEDIDOS(R_NFS_PEDIDOS.DT_EMIS,
                                                           R_NFS_PEDIDOS.CD_FIL,
                                                           R_NFS_PEDIDOS.NR_NF,
                                                           R_NFS_PEDIDOS.DS_SER,
                                                           R_NFS_PEDIDOS.NR_SUBSER,
                                                           R_PEDIDOS_FATURADOS.ISCPS_NU_SEQ,
                                                           R_PEDIDOS_FATURADOS.TRPGW_NU_PEDIDO_ORIGEM,
                                                           R_PEDIDOS_FATURADOS.TRPGW_TP_DOCTO)
            LOOP
               IF V_GRAVAR_CABEC = 'S' THEN
                  --
                  -- Gerar o registro do cabecalho do Pedido Saida
                  P_REC_CABPED := NULL;
                  --
                  P_REC_CABPED.NU_SEQ                  := NULL; -- será gerado no PR_INS_CAB_PEDIDO_SAIDA
                  P_REC_CABPED.CD_EMPRESA              := R_PEDIDOS_FATURADOS.IECPS_CD_EMPRESA;
                  P_REC_CABPED.CD_DEPOSITO             := R_PEDIDOS_FATURADOS.IECPS_CD_DEPOSITO;
                  P_REC_CABPED.NU_PEDIDO_ORIGEM        := R_PEDIDOS_FATURADOS.IECPS_NU_PEDIDO_ORIGEM;
                  P_REC_CABPED.CD_CLIENTE              := R_PEDIDOS_FATURADOS.IECPS_CD_CLIENTE;
                  P_REC_CABPED.CD_CNPJ_CLIENTE         := R_PEDIDOS_FATURADOS.IECPS_CD_CNPJ_CLIENTE;
                  P_REC_CABPED.CD_CARGA                := R_PEDIDOS_FATURADOS.IECPS_CD_CARGA;
                  P_REC_CABPED.CD_SITUACAO             := 3; -- FATURAMENTO
                  P_REC_CABPED.TP_PEDIDO               := R_PEDIDOS_FATURADOS.IECPS_TP_PEDIDO;
                  P_REC_CABPED.DS_TPPEDIDO             := R_PEDIDOS_FATURADOS.IECPS_DS_TPPEDIDO;
                  P_REC_CABPED.CD_PORTA                := R_PEDIDOS_FATURADOS.IECPS_CD_PORTA;
                  P_REC_CABPED.CD_TRANSPORTADORA       := R_PEDIDOS_FATURADOS.IECPS_CD_TRANSPORTADORA;
                  P_REC_CABPED.CD_CNPJ_TRANSPORTADORA  := R_PEDIDOS_FATURADOS.IECPS_CD_CNPJ_TRANSPORTADORA;
                  P_REC_CABPED.DS_TRANSPORTADORA       := R_PEDIDOS_FATURADOS.IECPS_DS_TRANSPORTADORA;
                  P_REC_CABPED.NU_DOC_ERP              := R_PEDIDOS_FATURADOS.IECPS_NU_DOC_ERP;
                  P_REC_CABPED.DS_CLIENTE_ENTREGA      := R_PEDIDOS_FATURADOS.IECPS_DS_CLIENTE_ENTREGA;
                  P_REC_CABPED.CD_CNPJ_CLIENTE_ENTREGA := R_PEDIDOS_FATURADOS.IECPS_CD_CNPJ_CLIENTE_ENTREGA;
                  P_REC_CABPED.DS_CLIENTE              := R_PEDIDOS_FATURADOS.IECPS_DS_CLIENTE;
                  P_REC_CABPED.DS_ENDERECO_ENTREGA     := R_PEDIDOS_FATURADOS.IECPS_DS_ENDERECO_ENTREGA;
                  P_REC_CABPED.NU_ENDERECO_ENTREGA     := R_PEDIDOS_FATURADOS.IECPS_NU_ENDERECO_ENTREGA;
                  P_REC_CABPED.DS_COMPLEMENTO_ENTREGA  := R_PEDIDOS_FATURADOS.IECPS_DS_COMPLEMENTO_ENTREGA;
                  P_REC_CABPED.DS_BAIRRO_ENTREGA       := R_PEDIDOS_FATURADOS.IECPS_DS_BAIRRO_ENTREGA;
                  P_REC_CABPED.DS_MUNICIPIO_ENTREGA    := R_PEDIDOS_FATURADOS.IECPS_DS_MUNICIPIO_ENTREGA;
                  P_REC_CABPED.CD_UF_ENTREGA           := R_PEDIDOS_FATURADOS.IECPS_CD_UF_ENTREGA;
                  P_REC_CABPED.CD_CEP_ENTREGA          := R_PEDIDOS_FATURADOS.IECPS_CD_CEP_ENTREGA;
                  P_REC_CABPED.NU_TELEFONE_ENTREGA     := R_PEDIDOS_FATURADOS.IECPS_NU_TELEFONE_ENTREGA;
                  P_REC_CABPED.VL_NOTA                 := R_PEDIDOS_FATURADOS.IECPS_VL_NOTA;
                  P_REC_CABPED.DT_ENTREGA              := R_PEDIDOS_FATURADOS.IECPS_DT_ENTREGA;
                  P_REC_CABPED.CD_AGENDA               := R_PEDIDOS_FATURADOS.IECPS_CD_AGENDA;
                  P_REC_CABPED.NU_SEQ_ENTREGA          := R_PEDIDOS_FATURADOS.IECPS_NU_SEQ_ENTREGA;
                  P_REC_CABPED.NU_PEDIDO               := R_PEDIDOS_FATURADOS.IECPS_NU_PEDIDO;
                  P_REC_CABPED.CD_CANAL                := R_PEDIDOS_FATURADOS.IECPS_CD_CANAL;
                  P_REC_CABPED.DS_CANAL                := R_PEDIDOS_FATURADOS.IECPS_DS_CANAL;
                  P_REC_CABPED.CD_ROTA                 := R_PEDIDOS_FATURADOS.IECPS_CD_ROTA;
                  P_REC_CABPED.DS_ROTA                 := R_PEDIDOS_FATURADOS.IECPS_DS_ROTA;
                  P_REC_CABPED.ID_SOLICITA_CONTROLE    := R_PEDIDOS_FATURADOS.IECPS_ID_SOLICITA_CONTROLE;
                  P_REC_CABPED.DT_FATURAMENTO          := R_PEDIDOS_FATURADOS.IECPS_DT_FATURAMENTO;
                  P_REC_CABPED.DT_ENTRADA              := R_PEDIDOS_FATURADOS.IECPS_DT_ENTRADA;
                  P_REC_CABPED.NU_OBJETO_POSTAGEM      := R_PEDIDOS_FATURADOS.IECPS_NU_OBJETO_POSTAGEM;
                  P_REC_CABPED.DS_OBSERVACAO           := R_PEDIDOS_FATURADOS.IECPS_DS_OBSERVACAO;
                  P_REC_CABPED.CD_MUNICIPIO_IBGE       := R_PEDIDOS_FATURADOS.IECPS_CD_MUNICIPIO_IBGE;
                  P_REC_CABPED.TP_FRETE                := R_PEDIDOS_FATURADOS.IECPS_TP_FRETE;
                  P_REC_CABPED.ID_CONTRIBUINTE_ICMS    := R_PEDIDOS_FATURADOS.IECPS_ID_CONTRIBUINTE_ICMS;
                  P_REC_CABPED.CD_PRODUTO_CATEGORIA    := R_PEDIDOS_FATURADOS.IECPS_CD_PRODUTO_CATEGORIA;
                  P_REC_CABPED.VLR_FRETE_RECEBER       := R_PEDIDOS_FATURADOS.IECPS_VLR_FRETE_RECEBER;
                  P_REC_CABPED.CD_TIPO_ENTREGA         := R_PEDIDOS_FATURADOS.IECPS_CD_TIPO_ENTREGA;
                  P_REC_CABPED.FILLER_1                := R_PEDIDOS_FATURADOS.IECPS_FILLER_1;
                  P_REC_CABPED.FILLER_2                := R_PEDIDOS_FATURADOS.IECPS_FILLER_2;
                  P_REC_CABPED.FILLER_3                := R_PEDIDOS_FATURADOS.IECPS_FILLER_3;
                  P_REC_CABPED.FILLER_4                := R_PEDIDOS_FATURADOS.IECPS_FILLER_4;
                  P_REC_CABPED.FILLER_5                := R_PEDIDOS_FATURADOS.IECPS_FILLER_5;
                  P_REC_CABPED.DS_PONTUACAO_CLIENTE    := R_PEDIDOS_FATURADOS.IECPS_DS_PONTUACAO_CLIENTE;
                  P_REC_CABPED.CD_FILIAL_VENDA         := R_PEDIDOS_FATURADOS.IECPS_CD_FILIAL_VENDA;
                  P_REC_CABPED.DS_MODAL_FRETE          := R_PEDIDOS_FATURADOS.IECPS_DS_MODAL_FRETE;
                  P_REC_CABPED.NU_VOLUME_TRANSPORTE    := R_PEDIDOS_FATURADOS.IECPS_NU_VOLUME_TRANSPORTE;
                  P_REC_CABPED.QT_PEDIDOS_CARGA        := R_PEDIDOS_FATURADOS.IECPS_QT_PEDIDOS_CARGA;
                  P_REC_CABPED.NU_ETIQUETA_MASTER      := R_PEDIDOS_FATURADOS.ISCPS_NU_ETIQUETA_MASTER;
                  P_REC_CABPED.NU_ORDEM_COMPRA         := R_PEDIDOS_FATURADOS.IECPS_NU_ORDEM_COMPRA;
                  P_REC_CABPED.TP_SERVICO_ENTREGA      := R_PEDIDOS_FATURADOS.IECPS_TP_SERVICO_ENTREGA;
                  P_REC_CABPED.DT_PAGAMENTO_PEDIDO     := R_PEDIDOS_FATURADOS.IECPS_DT_PAGAMENTO_PEDIDO;
                  P_REC_CABPED.DS_PLACA                := R_PEDIDOS_FATURADOS.IECPS_DS_PLACA;
                  P_REC_CABPED.ID_PROCESSADO           := 'N';
                  --
                  BEGIN
                     --
                     GC.PCK_GERAR_INTERF_WMS.PR_INS_CAB_PEDIDO_SAIDA(P_REC_CABPED);
                     --
                     V_GRAVAR_CABEC := 'N';
                  EXCEPTION
                     WHEN OTHERS THEN
                        V_ERRO_CAB            := 'Erro Retorno Pedido:[' || P_REC_CABPED.NU_PEDIDO_ORIGEM || '] ' ||
                                                 SQLERRM;
                        V_PROCESSAMENTO_OK_SN := 'N';
                  END;
               END IF;
               --
               IF V_PROCESSAMENTO_OK_SN = 'S' THEN
                  P_REC_DETPED                          := NULL;
                  P_REC_DETPED.NU_SEQ                   := P_REC_CABPED.NU_SEQ;
                  P_REC_DETPED.CD_EMPRESA               := R_ITENS_NFS_PEDIDOS.IEDPS_CD_EMPRESA;
                  P_REC_DETPED.CD_DEPOSITO              := R_ITENS_NFS_PEDIDOS.IEDPS_CD_DEPOSITO;
                  P_REC_DETPED.NU_PEDIDO_ORIGEM         := R_ITENS_NFS_PEDIDOS.IEDPS_NU_PEDIDO_ORIGEM;
                  P_REC_DETPED.CD_CLIENTE               := R_ITENS_NFS_PEDIDOS.IEDPS_CD_CLIENTE;
                  P_REC_DETPED.CD_PRODUTO               := R_ITENS_NFS_PEDIDOS.ISP_ID_PROD;
                  P_REC_DETPED.NU_ITEM_CORP             := R_ITENS_NFS_PEDIDOS.IEDPS_NU_ITEM_CORP;
                  P_REC_DETPED.QT_SEPARAR               := R_ITENS_NFS_PEDIDOS.ISP_QT_ITEM;
                  P_REC_DETPED.CD_SITUACAO              := P_REC_CABPED.CD_SITUACAO;
                  P_REC_DETPED.NU_LOTE                  := R_ITENS_NFS_PEDIDOS.IEDPS_NU_LOTE;
                  P_REC_DETPED.NU_NOTA                  := R_ITENS_NFS_PEDIDOS.ISP_NU_NOTA;
                  P_REC_DETPED.NU_SERIE_NOTA            := R_ITENS_NFS_PEDIDOS.ISP_NU_SERIE_NOTA;
                  P_REC_DETPED.CFOP                     := R_ITENS_NFS_PEDIDOS.ISP_CFOP;
                  P_REC_DETPED.DT_NOTA_FISCAL           := R_ITENS_NFS_PEDIDOS.ISP_DT_NOTA_FISCAL;
                  P_REC_DETPED.NU_PEDIDO                := R_ITENS_NFS_PEDIDOS.IEDPS_NU_PEDIDO;
                  P_REC_DETPED.ID_EMBALAGEM_PRESENTE    := R_ITENS_NFS_PEDIDOS.IEDPS_ID_EMBALAGEM_PRESENTE;
                  P_REC_DETPED.CAMPANHA                 := R_ITENS_NFS_PEDIDOS.IEDPS_CAMPANHA;
                  P_REC_DETPED.CD_CHAVE_DANFE           := R_ITENS_NFS_PEDIDOS.ISP_DANFE;
                  P_REC_DETPED.DS_AREA_ERP              := R_ITENS_NFS_PEDIDOS.IEDPS_DS_AREA_ERP;
                  P_REC_DETPED.FILLER_1                 := R_ITENS_NFS_PEDIDOS.IEDPS_FILLER_1;
                  P_REC_DETPED.FILLER_2                 := R_ITENS_NFS_PEDIDOS.IEDPS_FILLER_2;
                  P_REC_DETPED.FILLER_3                 := R_ITENS_NFS_PEDIDOS.IEDPS_FILLER_3;
                  P_REC_DETPED.FILLER_4                 := R_ITENS_NFS_PEDIDOS.IEDPS_FILLER_4;
                  P_REC_DETPED.FILLER_5                 := R_ITENS_NFS_PEDIDOS.IEDPS_FILLER_5;
                  P_REC_DETPED.CD_CARGA                 := R_ITENS_NFS_PEDIDOS.IEDPS_CD_CARGA;
                  P_REC_DETPED.NU_CTRL_ITEM             := R_ITENS_NFS_PEDIDOS.IEDPS_NU_CTRL_ITEM;
                  P_REC_DETPED.NU_ETIQUETA_MASTER       := R_ITENS_NFS_PEDIDOS.ISDPS_NU_ETIQUETA_MASTER;
                  P_REC_DETPED.DS_PRODUTO_PERSONALIZADO := R_ITENS_NFS_PEDIDOS.IEDPS_DS_PRODUTO_PERSONALIZADO;
                  P_REC_DETPED.DS_OBSERVACAO            := R_ITENS_NFS_PEDIDOS.IEDPS_DS_OBSERVACAO;
                  P_REC_DETPED.ID_PROCESSADO            := P_REC_CABPED.ID_PROCESSADO;
                  --
                  BEGIN
                     --
                     GC.PCK_GERAR_INTERF_WMS.PR_INS_DET_PEDIDO_SAIDA(P_REC_DETPED);
                     --
                     IF V_PROCESSAMENTO_OK_SN = 'S' THEN
                        UPDATE WMS.INT_S_DET_PEDIDO_SAIDA ISDPS
                           SET ISDPS.ID_PROCESSADO = 'P',
                               ISDPS.DS_PROCESSADO = 'RETORNO REALIZADO COM NU_SEQ:['||P_REC_CABPED.NU_SEQ||']'||' NF:['||R_ITENS_NFS_PEDIDOS.ISP_NU_NOTA||']',
                               ISDPS.DT_PROCESSADO = SYSDATE
                         WHERE ISDPS.ROWID = R_ITENS_NFS_PEDIDOS.CHAVE_ISDPS;
                     END IF;
                     --
                     V_QTDE_REGS := V_QTDE_REGS + 1;
                  EXCEPTION
                     WHEN DUP_VAL_ON_INDEX THEN -- CHAVE [NU_SEQ, NU_ITEM_CORP] NAO ALTERA O NU_NOTA
                       BEGIN
                         UPDATE WMS.INT_E_DET_PEDIDO_SAIDA IEDPS
                            SET IEDPS.QT_SEPARAR = NVL(IEDPS.QT_SEPARAR,0) + R_ITENS_NFS_PEDIDOS.ISP_QT_ITEM
                         WHERE IEDPS.CD_SITUACAO = 3
                           AND IEDPS.NU_PEDIDO_ORIGEM = R_ITENS_NFS_PEDIDOS.IEDPS_NU_PEDIDO_ORIGEM
                           AND IEDPS.NU_SEQ           = P_REC_CABPED.NU_SEQ
                           AND IEDPS.NU_ITEM_CORP     = R_ITENS_NFS_PEDIDOS.IEDPS_NU_ITEM_CORP
                           AND IEDPS.CD_PRODUTO       = R_ITENS_NFS_PEDIDOS.ISP_ID_PROD;
                        UPDATE WMS.INT_S_DET_PEDIDO_SAIDA ISDPS
                           SET ISDPS.ID_PROCESSADO = 'P',
                               ISDPS.DS_PROCESSADO = ISDPS.DS_PROCESSADO|| '/NF:['||R_ITENS_NFS_PEDIDOS.ISP_NU_NOTA||']',
                               ISDPS.DT_PROCESSADO = SYSDATE
                         WHERE ISDPS.ROWID = R_ITENS_NFS_PEDIDOS.CHAVE_ISDPS;
                       END;
                     WHEN OTHERS THEN
                        V_ERRO_DET            := 'Erro Retorno Pedido:[' || P_REC_CABPED.NU_PEDIDO_ORIGEM ||
                                                 '] Produto:[' || P_REC_DETPED.CD_PRODUTO || '] ' || SQLERRM;
                        V_PROCESSAMENTO_OK_SN := 'N';
                  END;
               END IF; -- DETALHE
            END LOOP; -- DETALHE
         END LOOP; -- CABECALHO
      EXCEPTION
         WHEN OTHERS THEN
            NULL;
      END;
      --
      IF V_PROCESSAMENTO_OK_SN = 'S' AND
         V_QTDE_REGS > 0 THEN
         UPDATE WMS.INT_S_CAB_PEDIDO_SAIDA ISCPS
            SET ISCPS.ID_PROCESSADO = 'P',
                ISCPS.DS_PROCESSADO = 'RETORNO REALIZADO COM NU_SEQ:['||P_REC_CABPED.NU_SEQ||']',
                ISCPS.DT_PROCESSADO = SYSDATE
          WHERE ISCPS.ROWID = R_PEDIDOS_FATURADOS.CHAVE_ISCPS;
         --
         COMMIT;
         --
      ELSE
         --
         ROLLBACK;
         --
      END IF;
      --
   END LOOP; -- PEDIDOS
EXCEPTION
   WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, 'PROCEDURE GC.PRC_RETORNAR_NFS_WMS_GC -> ERRO<' || D_SQLERRM || '> ');
END PRC_RETORNAR_NFS_WMS_GC;
/
CREATE OR REPLACE PUBLIC SYNONYM PRC_RETORNAR_NFS_WMS_GC FOR GC.PRC_RETORNAR_NFS_WMS_GC;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO GC_LOJA;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO SICA_RL_GC_GERAL;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO RL_GC_DTI;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO RL_EXEC_GC;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO RL_CONS_GC;
/
GRANT EXECUTE ON GC.PRC_RETORNAR_NFS_WMS_GC TO OMS_LINX;
/
